spring.application.name=attendance
spring.datasource.url = jdbc:postgresql://localhost:5432/attendance_db
spring.datasource.username = postgres
spring.datasource.password = aryajain

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret = what-is-this-world-without-art-just-a-piece-of-rock